server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URI:http://localhost:8084}
              predicates:
                - Path=/api/auth/**

            - id: user-service-register
              uri: ${USER_SERVICE_URI:http://localhost:8081}
              predicates:
                  - Path=/api/users
                  - Method=POST
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10

            - id: user-service
              uri: ${USER_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/users/**

            - id: task-service
              uri: ${TASK_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/api/tasks/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - ${FRONTEND_URL:http://localhost:4200}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true


jwt:
  secret: ${JWT_SECRET:0OL3hz0pZb6pqe6yKvcHFwCqKwIaQZmT9RlSMfgcmRx}